// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addNewTestPhase = `-- name: addNewTestPhase :exec
Insert Into "TestPhases" ("Name", "CreationDate", "CreationTime", "Selected")
values (?,?,?,?)
`

type addNewTestPhaseParams struct {
	Name         string
	CreationDate sql.NullString
	CreationTime sql.NullString
	Selected     int64
}

func (q *Queries) addNewTestPhase(ctx context.Context, arg addNewTestPhaseParams) error {
	_, err := q.db.ExecContext(ctx, addNewTestPhase,
		arg.Name,
		arg.CreationDate,
		arg.CreationTime,
		arg.Selected,
	)
	return err
}

const deselectTestPhase = `-- name: deselectTestPhase :exec
Update "TestPhases" set "Selected" = 0
`

func (q *Queries) deselectTestPhase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deselectTestPhase)
	return err
}

const getAllConfigs = `-- name: getAllConfigs :many
Select "ConfigName" from "Configurations"
`

func (q *Queries) getAllConfigs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConfigsForDownlinkLoss = `-- name: getAllConfigsForDownlinkLoss :many
Select "ConfigName" from "DownlinkLoss"
where "TestPhaseName" like ?
`

func (q *Queries) getAllConfigsForDownlinkLoss(ctx context.Context, testphasename string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigsForDownlinkLoss, testphasename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConfigsForTests = `-- name: getAllConfigsForTests :many
Select distinct "Configurations"."ConfigType", "Tests"."ConfigName" from "Tests"
inner join "Configurations" ON "Tests"."ConfigName" = "Configurations"."ConfigName"
`

type getAllConfigsForTestsRow struct {
	ConfigType string
	ConfigName string
}

func (q *Queries) getAllConfigsForTests(ctx context.Context) ([]getAllConfigsForTestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigsForTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getAllConfigsForTestsRow
	for rows.Next() {
		var i getAllConfigsForTestsRow
		if err := rows.Scan(&i.ConfigType, &i.ConfigName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConfigsForUplinkLoss = `-- name: getAllConfigsForUplinkLoss :many
Select "ConfigName" from "UplinkLoss"
where "TestPhaseName" like ?
`

func (q *Queries) getAllConfigsForUplinkLoss(ctx context.Context, testphasename string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigsForUplinkLoss, testphasename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConfigsWithTypes = `-- name: getAllConfigsWithTypes :many
Select "ConfigType", "ConfigName" from "Configurations"
`

type getAllConfigsWithTypesRow struct {
	ConfigType string
	ConfigName string
}

func (q *Queries) getAllConfigsWithTypes(ctx context.Context) ([]getAllConfigsWithTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigsWithTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getAllConfigsWithTypesRow
	for rows.Next() {
		var i getAllConfigsWithTypesRow
		if err := rows.Scan(&i.ConfigType, &i.ConfigName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConverterNames = `-- name: getAllConverterNames :many
Select "Name" from "UpDownConverter"
`

func (q *Queries) getAllConverterNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllConverterNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDeviceProfiles = `-- name: getAllDeviceProfiles :many
Select "DeviceProfileName" from "DeviceProfile"
`

func (q *Queries) getAllDeviceProfiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeviceProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceProfileName string
		if err := rows.Scan(&DeviceProfileName); err != nil {
			return nil, err
		}
		items = append(items, DeviceProfileName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDownlinkLossForTestPhase = `-- name: getAllDownlinkLossForTestPhase :many
Select ID, ConfigName, TestPhaseName, Profile from "DownlinkLoss"
where "TestPhaseName" = ?
`

func (q *Queries) getAllDownlinkLossForTestPhase(ctx context.Context, testphasename string) ([]DownlinkLoss, error) {
	rows, err := q.db.QueryContext(ctx, getAllDownlinkLossForTestPhase, testphasename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownlinkLoss
	for rows.Next() {
		var i DownlinkLoss
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.TestPhaseName,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLossMeasruementFrequencies = `-- name: getAllLossMeasruementFrequencies :many
Select "Description", "Frequency" from "LossMeasurementFrequencies"
Order by "ID" asc
`

type getAllLossMeasruementFrequenciesRow struct {
	Description string
	Frequency   float64
}

func (q *Queries) getAllLossMeasruementFrequencies(ctx context.Context) ([]getAllLossMeasruementFrequenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLossMeasruementFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getAllLossMeasruementFrequenciesRow
	for rows.Next() {
		var i getAllLossMeasruementFrequenciesRow
		if err := rows.Scan(&i.Description, &i.Frequency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLossMeasruementFrequencyNames = `-- name: getAllLossMeasruementFrequencyNames :many
Select "Description" from "LossMeasurementFrequencies"
Order by "ID" asc
`

func (q *Queries) getAllLossMeasruementFrequencyNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllLossMeasruementFrequencyNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Description string
		if err := rows.Scan(&Description); err != nil {
			return nil, err
		}
		items = append(items, Description)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPM = `-- name: getAllPM :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'PM' Order by "ID" asc
`

func (q *Queries) getAllPM(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPMAndPPM = `-- name: getAllPMAndPPM :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'PM' or "DeviceType" like 'PPM'
Order by "ID" asc
`

func (q *Queries) getAllPMAndPPM(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPMAndPPM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPPM = `-- name: getAllPPM :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'PPM' Order by "ID" asc
`

func (q *Queries) getAllPPM(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPPM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPathsInTSMConfig = `-- name: getAllPathsInTSMConfig :one
Select ID, Name, UplinkToSC, IncludePad, ExcludePad, UplinkToSA, UplinkToPM, TerminateUplink, DownlinkToSA, DownlinkToPM, AttnNumber, DownlinkToDC, InputPortName, SAPortName, PMPortName, OutputPortName from "TSMConfigurations"
Where "Name" like ?
`

func (q *Queries) getAllPathsInTSMConfig(ctx context.Context, name string) (TSMConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getAllPathsInTSMConfig, name)
	var i TSMConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UplinkToSC,
		&i.IncludePad,
		&i.ExcludePad,
		&i.UplinkToSA,
		&i.UplinkToPM,
		&i.TerminateUplink,
		&i.DownlinkToSA,
		&i.DownlinkToPM,
		&i.AttnNumber,
		&i.DownlinkToDC,
		&i.InputPortName,
		&i.SAPortName,
		&i.PMPortName,
		&i.OutputPortName,
	)
	return i, err
}

const getAllPayloadConfigs = `-- name: getAllPayloadConfigs :many
Select "ConfigName" from "Configurations"
where ConfigType like 'PL'
`

func (q *Queries) getAllPayloadConfigs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayloadConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPulseProfiles = `-- name: getAllPulseProfiles :many
Select "Name" from "PulseProfile"
`

func (q *Queries) getAllPulseProfiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPulseProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRxForFrequency = `-- name: getAllRxForFrequency :many
;

Select "RxName" from "SpecRx"
where "Frequency" = ?
`

func (q *Queries) getAllRxForFrequency(ctx context.Context, frequency int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllRxForFrequency, frequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var RxName string
		if err := rows.Scan(&RxName); err != nil {
			return nil, err
		}
		items = append(items, RxName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRxNames = `-- name: getAllRxNames :many
Select "RxName" from "SpecRx"
`

func (q *Queries) getAllRxNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllRxNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var RxName string
		if err := rows.Scan(&RxName); err != nil {
			return nil, err
		}
		items = append(items, RxName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSA = `-- name: getAllSA :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'SA' Order by "ID" asc
`

func (q *Queries) getAllSA(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSAAndVSA = `-- name: getAllSAAndVSA :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'SA' or "DeviceType" like 'VSA'
Order by "ID" asc
`

func (q *Queries) getAllSAAndVSA(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSAAndVSA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSG = `-- name: getAllSG :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'SG' Order by "ID" asc
`

func (q *Queries) getAllSG(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSG)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSpectrumProfiles = `-- name: getAllSpectrumProfiles :many
Select "Name" from "SpectrumProfile"
Order by "ID" asc
`

func (q *Queries) getAllSpectrumProfiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSpectrumProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTSM = `-- name: getAllTSM :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'TSM'
Order by "ID" asc
`

func (q *Queries) getAllTSM(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTSM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTSMConfigurations = `-- name: getAllTSMConfigurations :many
Select "Name" from "TSMConfigurations"
`

func (q *Queries) getAllTSMConfigurations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTSMConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTestForConfig = `-- name: getAllTestForConfig :many
Select "TestType", "TestCategory" from "Tests"
where "ConfigName" like ? and "TestType" not like "%RFUplink%"
`

type getAllTestForConfigRow struct {
	TestType     string
	TestCategory string
}

func (q *Queries) getAllTestForConfig(ctx context.Context, configname string) ([]getAllTestForConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTestForConfig, configname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getAllTestForConfigRow
	for rows.Next() {
		var i getAllTestForConfigRow
		if err := rows.Scan(&i.TestType, &i.TestCategory); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTestPhases = `-- name: getAllTestPhases :many
Select "Name" From "TestPhases"
Order by "Selected" Desc
`

func (q *Queries) getAllTestPhases(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllTestPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUplinkLossForTestPhase = `-- name: getAllUplinkLossForTestPhase :many
Select ID, ConfigName, TestPhaseName, Profile from "UplinkLoss"
where "TestPhaseName" = ?
`

func (q *Queries) getAllUplinkLossForTestPhase(ctx context.Context, testphasename string) ([]UplinkLoss, error) {
	rows, err := q.db.QueryContext(ctx, getAllUplinkLossForTestPhase, testphasename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UplinkLoss
	for rows.Next() {
		var i UplinkLoss
		if err := rows.Scan(
			&i.ID,
			&i.ConfigName,
			&i.TestPhaseName,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVSA = `-- name: getAllVSA :many
Select "DeviceName" from "Devices"
Where "DeviceType" like 'VSA' Order by "ID" asc
`

func (q *Queries) getAllVSA(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllVSA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var DeviceName string
		if err := rows.Scan(&DeviceName); err != nil {
			return nil, err
		}
		items = append(items, DeviceName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommandsInPowerProfile = `-- name: getCommandsInPowerProfile :one
Select "NoOfCommandsAtThreshold", "NoOfCommandsAtOtherLevels" from "PowerProfile"
where "Name" like ?
`

type getCommandsInPowerProfileRow struct {
	NoOfCommandsAtThreshold   int64
	NoOfCommandsAtOtherLevels int64
}

func (q *Queries) getCommandsInPowerProfile(ctx context.Context, name string) (getCommandsInPowerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getCommandsInPowerProfile, name)
	var i getCommandsInPowerProfileRow
	err := row.Scan(&i.NoOfCommandsAtThreshold, &i.NoOfCommandsAtOtherLevels)
	return i, err
}

const getConfigsForUplink = `-- name: getConfigsForUplink :many
Select "ConfigName" from "Tests"
Where "TestType" like "RFUplink"
`

func (q *Queries) getConfigsForUplink(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getConfigsForUplink)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigurationDetails = `-- name: getConfigurationDetails :one
Select ID, ConfigName, ConfigType, RxName, TxName, TpName, PayloadName, TSMConfigurationName, CortexIFM, IntermediateFrequency, ProgrammableAttnUsed, DeviceProfileName from "Configurations"
where "ConfigName" like ?
`

func (q *Queries) getConfigurationDetails(ctx context.Context, configname string) (Configuration, error) {
	row := q.db.QueryRowContext(ctx, getConfigurationDetails, configname)
	var i Configuration
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigType,
		&i.RxName,
		&i.TxName,
		&i.TpName,
		&i.PayloadName,
		&i.TSMConfigurationName,
		&i.CortexIFM,
		&i.IntermediateFrequency,
		&i.ProgrammableAttnUsed,
		&i.DeviceProfileName,
	)
	return i, err
}

const getConfigurationNamesForTSMConfig = `-- name: getConfigurationNamesForTSMConfig :many
Select "ConfigName" from "Configurations"
where "TSMConfigurationName" like ?
`

func (q *Queries) getConfigurationNamesForTSMConfig(ctx context.Context, tsmconfigurationname string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getConfigurationNamesForTSMConfig, tsmconfigurationname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ConfigName string
		if err := rows.Scan(&ConfigName); err != nil {
			return nil, err
		}
		items = append(items, ConfigName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConverterDetails = `-- name: getConverterDetails :one
Select ID, Name, InputFrequency, OutputFrequency, MaxPowerCable, MinPowerCable, MaxPowerRadiated, MinPowerRadiated from "UpDownConverter"
where "Name" like ?
`

func (q *Queries) getConverterDetails(ctx context.Context, name string) (UpDownConverter, error) {
	row := q.db.QueryRowContext(ctx, getConverterDetails, name)
	var i UpDownConverter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputFrequency,
		&i.OutputFrequency,
		&i.MaxPowerCable,
		&i.MinPowerCable,
		&i.MaxPowerRadiated,
		&i.MinPowerRadiated,
	)
	return i, err
}

const getDeviceDetails = `-- name: getDeviceDetails :one
Select ID, DeviceName, DeviceMake, DeviceType, IPAddress, ControlPort, AlternateControlPort, ReadPort, DopplerPort, TimeoutInMillisecs from "Devices"
Where "DeviceName" like ?
`

func (q *Queries) getDeviceDetails(ctx context.Context, devicename string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceDetails, devicename)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.DeviceMake,
		&i.DeviceType,
		&i.IPAddress,
		&i.ControlPort,
		&i.AlternateControlPort,
		&i.ReadPort,
		&i.DopplerPort,
		&i.TimeoutInMillisecs,
	)
	return i, err
}

const getDownlinkLoss = `-- name: getDownlinkLoss :one
Select "Profile" from "DownlinkLoss"
where "ConfigName" like ? and "TestPhaseName" like ?
`

type getDownlinkLossParams struct {
	ConfigName    string
	TestPhaseName string
}

func (q *Queries) getDownlinkLoss(ctx context.Context, arg getDownlinkLossParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDownlinkLoss, arg.ConfigName, arg.TestPhaseName)
	var Profile string
	err := row.Scan(&Profile)
	return Profile, err
}

const getDownlinkPowerProfile = `-- name: getDownlinkPowerProfile :one
Select ID, Name, PMChannel, OccupiedBW from "DownlinkPowerProfile"
where "Name" like ?
`

func (q *Queries) getDownlinkPowerProfile(ctx context.Context, name sql.NullString) (DownlinkPowerProfile, error) {
	row := q.db.QueryRowContext(ctx, getDownlinkPowerProfile, name)
	var i DownlinkPowerProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PMChannel,
		&i.OccupiedBW,
	)
	return i, err
}

const getFrequencyForLossMeasurement = `-- name: getFrequencyForLossMeasurement :one
Select "Frequency" from "LossMeasurementFrequencies"
Where "Description" = ?
`

func (q *Queries) getFrequencyForLossMeasurement(ctx context.Context, description string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getFrequencyForLossMeasurement, description)
	var Frequency float64
	err := row.Scan(&Frequency)
	return Frequency, err
}

const getFrequencyProfile = `-- name: getFrequencyProfile :one
Select ID, Name, MaxFrequency, StepSize, CommandingRequired, DopplerFile from "FrequencyProfile"
where "Name" like ?
`

func (q *Queries) getFrequencyProfile(ctx context.Context, name string) (FrequencyProfile, error) {
	row := q.db.QueryRowContext(ctx, getFrequencyProfile, name)
	var i FrequencyProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxFrequency,
		&i.StepSize,
		&i.CommandingRequired,
		&i.DopplerFile,
	)
	return i, err
}

const getFullPulseSpecs = `-- name: getFullPulseSpecs :one
Select SpecID, ConfigName, ResolutionMode, OnTime, CenterFrequency, UplinkPower, PeakPower, PeakPowerTolerance, AveragePower, AveragePowerTolerance, DutyCycle, DutyCycleTolerance, PulsePeriod, PulsePeriodTolerance, ReplicaPeriod, ReplicaPeriodTolerance, PulseWidth, PulseWidthTolerance, PulseSeperation, PulseSeperationTolerance, RiseTime, RiseTimeTolerance, FallTime, FallTimeTolerance, AverageTxPower, AverageTxPowerTolerance, ChirpBandwidth, ChirpBandwidthTolerance, RepetitionRate, RepetitionRateTolerance, ReplicaRate, ReplicaRateTolerance, FrequencyShift, FrequencyShiftTolerance, Droop, DroopTolerance, Phase, PhaseTolerance, Overshoot, OvershootTolerance, ChirpRate, ChirpRateTolerance, ChirpRateDeviation, ChirpRateDeviationTolerance, Ripple, RippleTolerance from "SpecPL" where "ConfigName" = ? and ("ResolutionMode" not in ("HR","LR") or "ResolutionMode" is null)
`

func (q *Queries) getFullPulseSpecs(ctx context.Context, configname string) (SpecPL, error) {
	row := q.db.QueryRowContext(ctx, getFullPulseSpecs, configname)
	var i SpecPL
	err := row.Scan(
		&i.SpecID,
		&i.ConfigName,
		&i.ResolutionMode,
		&i.OnTime,
		&i.CenterFrequency,
		&i.UplinkPower,
		&i.PeakPower,
		&i.PeakPowerTolerance,
		&i.AveragePower,
		&i.AveragePowerTolerance,
		&i.DutyCycle,
		&i.DutyCycleTolerance,
		&i.PulsePeriod,
		&i.PulsePeriodTolerance,
		&i.ReplicaPeriod,
		&i.ReplicaPeriodTolerance,
		&i.PulseWidth,
		&i.PulseWidthTolerance,
		&i.PulseSeperation,
		&i.PulseSeperationTolerance,
		&i.RiseTime,
		&i.RiseTimeTolerance,
		&i.FallTime,
		&i.FallTimeTolerance,
		&i.AverageTxPower,
		&i.AverageTxPowerTolerance,
		&i.ChirpBandwidth,
		&i.ChirpBandwidthTolerance,
		&i.RepetitionRate,
		&i.RepetitionRateTolerance,
		&i.ReplicaRate,
		&i.ReplicaRateTolerance,
		&i.FrequencyShift,
		&i.FrequencyShiftTolerance,
		&i.Droop,
		&i.DroopTolerance,
		&i.Phase,
		&i.PhaseTolerance,
		&i.Overshoot,
		&i.OvershootTolerance,
		&i.ChirpRate,
		&i.ChirpRateTolerance,
		&i.ChirpRateDeviation,
		&i.ChirpRateDeviationTolerance,
		&i.Ripple,
		&i.RippleTolerance,
	)
	return i, err
}

const getGTxFromDeviceProfile = `-- name: getGTxFromDeviceProfile :one
Select "GTxName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getGTxFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getGTxFromDeviceProfile, deviceprofilename)
	var GTxName sql.NullString
	err := row.Scan(&GTxName)
	return GTxName, err
}

const getPLFrequency = `-- name: getPLFrequency :one
Select "CenterFrequency" from "SpecPL"
where "ConfigName" like ?
`

func (q *Queries) getPLFrequency(ctx context.Context, configname string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPLFrequency, configname)
	var CenterFrequency float64
	err := row.Scan(&CenterFrequency)
	return CenterFrequency, err
}

const getPMFromDeviceProfile = `-- name: getPMFromDeviceProfile :one
Select "PMName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getPMFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPMFromDeviceProfile, deviceprofilename)
	var PMName sql.NullString
	err := row.Scan(&PMName)
	return PMName, err
}

const getPPMFromDeviceProfile = `-- name: getPPMFromDeviceProfile :one
Select "PPMName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getPPMFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPPMFromDeviceProfile, deviceprofilename)
	var PPMName sql.NullString
	err := row.Scan(&PPMName)
	return PPMName, err
}

const getPowerLevels = `-- name: getPowerLevels :one
Select "PowerLevels" from "PowerProfile"
where "Name" like ?
`

func (q *Queries) getPowerLevels(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPowerLevels, name)
	var PowerLevels string
	err := row.Scan(&PowerLevels)
	return PowerLevels, err
}

const getPulseParameters = `-- name: getPulseParameters :one
Select ID, Name, TransientON, IQOn, AcquisitionTime, SweepTime, SweepCount, FilterType, FilterBandwidth, YTop, ThresholdLevel, Hysterisis, PPMTriggerLevel, PPMReferenceLevel, PPMYDivision, PPMChannel from "PulseProfile"
where "Name" = ?
`

func (q *Queries) getPulseParameters(ctx context.Context, name string) (PulseProfile, error) {
	row := q.db.QueryRowContext(ctx, getPulseParameters, name)
	var i PulseProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransientON,
		&i.IQOn,
		&i.AcquisitionTime,
		&i.SweepTime,
		&i.SweepCount,
		&i.FilterType,
		&i.FilterBandwidth,
		&i.YTop,
		&i.ThresholdLevel,
		&i.Hysterisis,
		&i.PPMTriggerLevel,
		&i.PPMReferenceLevel,
		&i.PPMYDivision,
		&i.PPMChannel,
	)
	return i, err
}

const getPulseSpecHRMode = `-- name: getPulseSpecHRMode :one
Select SpecID, ConfigName, ResolutionMode, OnTime, CenterFrequency, UplinkPower, PeakPower, PeakPowerTolerance, AveragePower, AveragePowerTolerance, DutyCycle, DutyCycleTolerance, PulsePeriod, PulsePeriodTolerance, ReplicaPeriod, ReplicaPeriodTolerance, PulseWidth, PulseWidthTolerance, PulseSeperation, PulseSeperationTolerance, RiseTime, RiseTimeTolerance, FallTime, FallTimeTolerance, AverageTxPower, AverageTxPowerTolerance, ChirpBandwidth, ChirpBandwidthTolerance, RepetitionRate, RepetitionRateTolerance, ReplicaRate, ReplicaRateTolerance, FrequencyShift, FrequencyShiftTolerance, Droop, DroopTolerance, Phase, PhaseTolerance, Overshoot, OvershootTolerance, ChirpRate, ChirpRateTolerance, ChirpRateDeviation, ChirpRateDeviationTolerance, Ripple, RippleTolerance from "SpecPL" where "ConfigName" = ? and "ResolutionMode" = "HR"
`

func (q *Queries) getPulseSpecHRMode(ctx context.Context, configname string) (SpecPL, error) {
	row := q.db.QueryRowContext(ctx, getPulseSpecHRMode, configname)
	var i SpecPL
	err := row.Scan(
		&i.SpecID,
		&i.ConfigName,
		&i.ResolutionMode,
		&i.OnTime,
		&i.CenterFrequency,
		&i.UplinkPower,
		&i.PeakPower,
		&i.PeakPowerTolerance,
		&i.AveragePower,
		&i.AveragePowerTolerance,
		&i.DutyCycle,
		&i.DutyCycleTolerance,
		&i.PulsePeriod,
		&i.PulsePeriodTolerance,
		&i.ReplicaPeriod,
		&i.ReplicaPeriodTolerance,
		&i.PulseWidth,
		&i.PulseWidthTolerance,
		&i.PulseSeperation,
		&i.PulseSeperationTolerance,
		&i.RiseTime,
		&i.RiseTimeTolerance,
		&i.FallTime,
		&i.FallTimeTolerance,
		&i.AverageTxPower,
		&i.AverageTxPowerTolerance,
		&i.ChirpBandwidth,
		&i.ChirpBandwidthTolerance,
		&i.RepetitionRate,
		&i.RepetitionRateTolerance,
		&i.ReplicaRate,
		&i.ReplicaRateTolerance,
		&i.FrequencyShift,
		&i.FrequencyShiftTolerance,
		&i.Droop,
		&i.DroopTolerance,
		&i.Phase,
		&i.PhaseTolerance,
		&i.Overshoot,
		&i.OvershootTolerance,
		&i.ChirpRate,
		&i.ChirpRateTolerance,
		&i.ChirpRateDeviation,
		&i.ChirpRateDeviationTolerance,
		&i.Ripple,
		&i.RippleTolerance,
	)
	return i, err
}

const getPulseSpecLRMode = `-- name: getPulseSpecLRMode :one
Select SpecID, ConfigName, ResolutionMode, OnTime, CenterFrequency, UplinkPower, PeakPower, PeakPowerTolerance, AveragePower, AveragePowerTolerance, DutyCycle, DutyCycleTolerance, PulsePeriod, PulsePeriodTolerance, ReplicaPeriod, ReplicaPeriodTolerance, PulseWidth, PulseWidthTolerance, PulseSeperation, PulseSeperationTolerance, RiseTime, RiseTimeTolerance, FallTime, FallTimeTolerance, AverageTxPower, AverageTxPowerTolerance, ChirpBandwidth, ChirpBandwidthTolerance, RepetitionRate, RepetitionRateTolerance, ReplicaRate, ReplicaRateTolerance, FrequencyShift, FrequencyShiftTolerance, Droop, DroopTolerance, Phase, PhaseTolerance, Overshoot, OvershootTolerance, ChirpRate, ChirpRateTolerance, ChirpRateDeviation, ChirpRateDeviationTolerance, Ripple, RippleTolerance from "SpecPL" where "ConfigName" = ? and "ResolutionMode" = "LR"
`

func (q *Queries) getPulseSpecLRMode(ctx context.Context, configname string) (SpecPL, error) {
	row := q.db.QueryRowContext(ctx, getPulseSpecLRMode, configname)
	var i SpecPL
	err := row.Scan(
		&i.SpecID,
		&i.ConfigName,
		&i.ResolutionMode,
		&i.OnTime,
		&i.CenterFrequency,
		&i.UplinkPower,
		&i.PeakPower,
		&i.PeakPowerTolerance,
		&i.AveragePower,
		&i.AveragePowerTolerance,
		&i.DutyCycle,
		&i.DutyCycleTolerance,
		&i.PulsePeriod,
		&i.PulsePeriodTolerance,
		&i.ReplicaPeriod,
		&i.ReplicaPeriodTolerance,
		&i.PulseWidth,
		&i.PulseWidthTolerance,
		&i.PulseSeperation,
		&i.PulseSeperationTolerance,
		&i.RiseTime,
		&i.RiseTimeTolerance,
		&i.FallTime,
		&i.FallTimeTolerance,
		&i.AverageTxPower,
		&i.AverageTxPowerTolerance,
		&i.ChirpBandwidth,
		&i.ChirpBandwidthTolerance,
		&i.RepetitionRate,
		&i.RepetitionRateTolerance,
		&i.ReplicaRate,
		&i.ReplicaRateTolerance,
		&i.FrequencyShift,
		&i.FrequencyShiftTolerance,
		&i.Droop,
		&i.DroopTolerance,
		&i.Phase,
		&i.PhaseTolerance,
		&i.Overshoot,
		&i.OvershootTolerance,
		&i.ChirpRate,
		&i.ChirpRateTolerance,
		&i.ChirpRateDeviation,
		&i.ChirpRateDeviationTolerance,
		&i.Ripple,
		&i.RippleTolerance,
	)
	return i, err
}

const getRxDetails = `-- name: getRxDetails :one
Select ID, RxName, Frequency, MaxPower, TCSubCarrierFrequency, ModulationScheme, AcquisitionOffset, SweepRange, SweepRate, TCModIndex, FrequencyDeviationFM, CodeRateInMcps from "SpecRx"
where "RxName" = ?
`

func (q *Queries) getRxDetails(ctx context.Context, rxname string) (SpecRx, error) {
	row := q.db.QueryRowContext(ctx, getRxDetails, rxname)
	var i SpecRx
	err := row.Scan(
		&i.ID,
		&i.RxName,
		&i.Frequency,
		&i.MaxPower,
		&i.TCSubCarrierFrequency,
		&i.ModulationScheme,
		&i.AcquisitionOffset,
		&i.SweepRange,
		&i.SweepRate,
		&i.TCModIndex,
		&i.FrequencyDeviationFM,
		&i.CodeRateInMcps,
	)
	return i, err
}

const getRxFrequency = `-- name: getRxFrequency :one
Select "Frequency" from "SpecRx"
where "RxName" like ?
`

func (q *Queries) getRxFrequency(ctx context.Context, rxname string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRxFrequency, rxname)
	var Frequency int64
	err := row.Scan(&Frequency)
	return Frequency, err
}

const getRxTMTC = `-- name: getRxTMTC :one
Select RxName, LockStatusMnemonic, LockStatusValue, BSLockStatusMnemonic, BSLockStatusValue, AGCMnemonic, LoopStressMnemonic, CommandCounterMnemonic, TestCommandSet, TestCommandReset from "SpecRxTMTC"
where "RxName" like ?
`

func (q *Queries) getRxTMTC(ctx context.Context, rxname string) (SpecRxTMTC, error) {
	row := q.db.QueryRowContext(ctx, getRxTMTC, rxname)
	var i SpecRxTMTC
	err := row.Scan(
		&i.RxName,
		&i.LockStatusMnemonic,
		&i.LockStatusValue,
		&i.BSLockStatusMnemonic,
		&i.BSLockStatusValue,
		&i.AGCMnemonic,
		&i.LoopStressMnemonic,
		&i.CommandCounterMnemonic,
		&i.TestCommandSet,
		&i.TestCommandReset,
	)
	return i, err
}

const getSAFromDeviceProfile = `-- name: getSAFromDeviceProfile :one
Select "SAName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getSAFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSAFromDeviceProfile, deviceprofilename)
	var SAName sql.NullString
	err := row.Scan(&SAName)
	return SAName, err
}

const getSGFromDeviceProfile = `-- name: getSGFromDeviceProfile :one
Select "SGName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getSGFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSGFromDeviceProfile, deviceprofilename)
	var SGName sql.NullString
	err := row.Scan(&SGName)
	return SGName, err
}

const getSelectedTestPhase = `-- name: getSelectedTestPhase :one
Select "Name" From "TestPhases"
Where "Selected" = 1
`

func (q *Queries) getSelectedTestPhase(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSelectedTestPhase)
	var Name string
	err := row.Scan(&Name)
	return Name, err
}

const getSpecTransponder = `-- name: getSpecTransponder :one
Select TpName, RangingID, RangingName, ToneFrequency, UplinkToneMIOnlyRanging, UplinkToneMISimultaneousCmdAndRanging, TCMISimultaneousCmdAndRanging, DownlinkMI, AllowedDownlinkMIDeviation, AvailableForCommanding from "SpecTpRanging" where "TpName" like ?
`

func (q *Queries) getSpecTransponder(ctx context.Context, tpname string) (SpecTpRanging, error) {
	row := q.db.QueryRowContext(ctx, getSpecTransponder, tpname)
	var i SpecTpRanging
	err := row.Scan(
		&i.TpName,
		&i.RangingID,
		&i.RangingName,
		&i.ToneFrequency,
		&i.UplinkToneMIOnlyRanging,
		&i.UplinkToneMISimultaneousCmdAndRanging,
		&i.TCMISimultaneousCmdAndRanging,
		&i.DownlinkMI,
		&i.AllowedDownlinkMIDeviation,
		&i.AvailableForCommanding,
	)
	return i, err
}

const getSpectrumProfile = `-- name: getSpectrumProfile :one
Select ID, Name, CenterFrequency, Span, RBW, VBW from "SpectrumProfile"
Where "Name" like ?
`

func (q *Queries) getSpectrumProfile(ctx context.Context, name string) (SpectrumProfile, error) {
	row := q.db.QueryRowContext(ctx, getSpectrumProfile, name)
	var i SpectrumProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CenterFrequency,
		&i.Span,
		&i.RBW,
		&i.VBW,
	)
	return i, err
}

const getSpexTxSubCarriersDetails = `-- name: getSpexTxSubCarriersDetails :many
Select TxName, SubCarrierID, SubCarrierName, Frequency, ModIndex, AllowedModIndexDeviation, PeakFrequencyDeviation, AlwaysPresent from "SpecTxSubCarriers"
where "TxName" like ?
`

func (q *Queries) getSpexTxSubCarriersDetails(ctx context.Context, txname string) ([]SpecTxSubCarrier, error) {
	rows, err := q.db.QueryContext(ctx, getSpexTxSubCarriersDetails, txname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecTxSubCarrier
	for rows.Next() {
		var i SpecTxSubCarrier
		if err := rows.Scan(
			&i.TxName,
			&i.SubCarrierID,
			&i.SubCarrierName,
			&i.Frequency,
			&i.ModIndex,
			&i.AllowedModIndexDeviation,
			&i.PeakFrequencyDeviation,
			&i.AlwaysPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTMParameters = `-- name: getTMParameters :one
Select ID, Name, PreRequisiteTM, LogTM from "TMProfile"
Where "Name" like ?
`

func (q *Queries) getTMParameters(ctx context.Context, name string) (TMProfile, error) {
	row := q.db.QueryRowContext(ctx, getTMParameters, name)
	var i TMProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PreRequisiteTM,
		&i.LogTM,
	)
	return i, err
}

const getTRMParameters = `-- name: getTRMParameters :one
Select ID, Name, NoOfTRMs, TimePerTRMInSecs, DelayBeforeFirstReadInSecs from "TRMProfile" where "Name" = ?
`

func (q *Queries) getTRMParameters(ctx context.Context, name sql.NullString) (TRMProfile, error) {
	row := q.db.QueryRowContext(ctx, getTRMParameters, name)
	var i TRMProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NoOfTRMs,
		&i.TimePerTRMInSecs,
		&i.DelayBeforeFirstReadInSecs,
	)
	return i, err
}

const getTSMConfigNameForConfig = `-- name: getTSMConfigNameForConfig :one
Select "TSMConfigurationName" from "Configurations"
Where "ConfigName" like ?
`

func (q *Queries) getTSMConfigNameForConfig(ctx context.Context, configname string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTSMConfigNameForConfig, configname)
	var TSMConfigurationName string
	err := row.Scan(&TSMConfigurationName)
	return TSMConfigurationName, err
}

const getTSMFromDeviceProfile = `-- name: getTSMFromDeviceProfile :one
Select "TSMName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getTSMFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTSMFromDeviceProfile, deviceprofilename)
	var TSMName sql.NullString
	err := row.Scan(&TSMName)
	return TSMName, err
}

const getTestWithCategory = `-- name: getTestWithCategory :one
Select ID, ConfigName, TestType, TestCategory, ULProfileName, DLProfileName, PowerProfileName, FrequencyProfileName, DownlinkPowerProfileName, PulseProfileName, TRMProfileName, TMProfileName from "Tests"
where "ConfigName" like ? and "TestType" like ? and "TestCategory" like ?
`

type getTestWithCategoryParams struct {
	ConfigName   string
	TestType     string
	TestCategory string
}

func (q *Queries) getTestWithCategory(ctx context.Context, arg getTestWithCategoryParams) (Test, error) {
	row := q.db.QueryRowContext(ctx, getTestWithCategory, arg.ConfigName, arg.TestType, arg.TestCategory)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.TestType,
		&i.TestCategory,
		&i.ULProfileName,
		&i.DLProfileName,
		&i.PowerProfileName,
		&i.FrequencyProfileName,
		&i.DownlinkPowerProfileName,
		&i.PulseProfileName,
		&i.TRMProfileName,
		&i.TMProfileName,
	)
	return i, err
}

const getTestWithoutCategory = `-- name: getTestWithoutCategory :one
Select ID, ConfigName, TestType, TestCategory, ULProfileName, DLProfileName, PowerProfileName, FrequencyProfileName, DownlinkPowerProfileName, PulseProfileName, TRMProfileName, TMProfileName from "Tests"
Where "ConfigName" like ? and "TestType" like  ?
`

type getTestWithoutCategoryParams struct {
	ConfigName string
	TestType   string
}

func (q *Queries) getTestWithoutCategory(ctx context.Context, arg getTestWithoutCategoryParams) (Test, error) {
	row := q.db.QueryRowContext(ctx, getTestWithoutCategory, arg.ConfigName, arg.TestType)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.TestType,
		&i.TestCategory,
		&i.ULProfileName,
		&i.DLProfileName,
		&i.PowerProfileName,
		&i.FrequencyProfileName,
		&i.DownlinkPowerProfileName,
		&i.PulseProfileName,
		&i.TRMProfileName,
		&i.TMProfileName,
	)
	return i, err
}

const getTxFrequency = `-- name: getTxFrequency :one
Select "Frequency" from "SpecTx"
where "TxName" like ?
`

func (q *Queries) getTxFrequency(ctx context.Context, txname string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTxFrequency, txname)
	var Frequency int64
	err := row.Scan(&Frequency)
	return Frequency, err
}

const getTxHarmonics = `-- name: getTxHarmonics :many
Select TxName, HarmonicsID, HarmonicType, HarmonicsName, Frequency, TotalLossFromTxToSA from "SpecTxHarmonics"
where "TxName" like ?
`

func (q *Queries) getTxHarmonics(ctx context.Context, txname string) ([]SpecTxHarmonic, error) {
	rows, err := q.db.QueryContext(ctx, getTxHarmonics, txname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecTxHarmonic
	for rows.Next() {
		var i SpecTxHarmonic
		if err := rows.Scan(
			&i.TxName,
			&i.HarmonicsID,
			&i.HarmonicType,
			&i.HarmonicsName,
			&i.Frequency,
			&i.TotalLossFromTxToSA,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTxSpecs = `-- name: getTxSpecs :one
Select TxID, TxName, Frequency, Power, Spurious, Harmonics, AllowedFrequencyDeviation, AllowedPowerDevaition, ModulationScheme, IsBurst, BurstTime from "SpecTx"
where "TxName" like ?
`

func (q *Queries) getTxSpecs(ctx context.Context, txname string) (SpecTx, error) {
	row := q.db.QueryRowContext(ctx, getTxSpecs, txname)
	var i SpecTx
	err := row.Scan(
		&i.TxID,
		&i.TxName,
		&i.Frequency,
		&i.Power,
		&i.Spurious,
		&i.Harmonics,
		&i.AllowedFrequencyDeviation,
		&i.AllowedPowerDevaition,
		&i.ModulationScheme,
		&i.IsBurst,
		&i.BurstTime,
	)
	return i, err
}

const getTxsubCarriers = `-- name: getTxsubCarriers :one
Select TxName, SubCarrierID, SubCarrierName, Frequency, ModIndex, AllowedModIndexDeviation, PeakFrequencyDeviation, AlwaysPresent from "SpecTxSubCarriers"
where "TxName" like ? and "SubCarrierName" like ?
`

type getTxsubCarriersParams struct {
	TxName         string
	SubCarrierName string
}

func (q *Queries) getTxsubCarriers(ctx context.Context, arg getTxsubCarriersParams) (SpecTxSubCarrier, error) {
	row := q.db.QueryRowContext(ctx, getTxsubCarriers, arg.TxName, arg.SubCarrierName)
	var i SpecTxSubCarrier
	err := row.Scan(
		&i.TxName,
		&i.SubCarrierID,
		&i.SubCarrierName,
		&i.Frequency,
		&i.ModIndex,
		&i.AllowedModIndexDeviation,
		&i.PeakFrequencyDeviation,
		&i.AlwaysPresent,
	)
	return i, err
}

const getUplinkLoss = `-- name: getUplinkLoss :one
Select "Profile" from "UplinkLoss"
where "ConfigName" like ? and "TestPhaseName" like ?
`

type getUplinkLossParams struct {
	ConfigName    string
	TestPhaseName string
}

func (q *Queries) getUplinkLoss(ctx context.Context, arg getUplinkLossParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUplinkLoss, arg.ConfigName, arg.TestPhaseName)
	var Profile string
	err := row.Scan(&Profile)
	return Profile, err
}

const getVSAFromDeviceProfile = `-- name: getVSAFromDeviceProfile :one
Select "VSAName" from "DeviceProfile"
where "DeviceProfileName" like ?
`

func (q *Queries) getVSAFromDeviceProfile(ctx context.Context, deviceprofilename string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getVSAFromDeviceProfile, deviceprofilename)
	var VSAName sql.NullString
	err := row.Scan(&VSAName)
	return VSAName, err
}

const insertDownlinkLoss = `-- name: insertDownlinkLoss :exec
Insert into "DownlinkLoss" ("ConfigName", "TestPhaseName", "Profile")
values (?,?,?)
`

type insertDownlinkLossParams struct {
	ConfigName    string
	TestPhaseName string
	Profile       string
}

func (q *Queries) insertDownlinkLoss(ctx context.Context, arg insertDownlinkLossParams) error {
	_, err := q.db.ExecContext(ctx, insertDownlinkLoss, arg.ConfigName, arg.TestPhaseName, arg.Profile)
	return err
}

const insertUplinkLoss = `-- name: insertUplinkLoss :exec
Insert into "UplinkLoss" ("ConfigName", "TestPhaseName", "Profile")
values (?,?,?)
`

type insertUplinkLossParams struct {
	ConfigName    string
	TestPhaseName string
	Profile       string
}

func (q *Queries) insertUplinkLoss(ctx context.Context, arg insertUplinkLossParams) error {
	_, err := q.db.ExecContext(ctx, insertUplinkLoss, arg.ConfigName, arg.TestPhaseName, arg.Profile)
	return err
}

const selectTestPhase = `-- name: selectTestPhase :exec
Update "TestPhases" set "Selected" = 1
where "Name" = ?
`

func (q *Queries) selectTestPhase(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, selectTestPhase, name)
	return err
}

const updateDownlinkLoss = `-- name: updateDownlinkLoss :exec
Update "DownlinkLoss" set "Profile"  = ?
where "ConfigName" like ? and "TestPhaseName" like ?
`

type updateDownlinkLossParams struct {
	Profile       string
	ConfigName    string
	TestPhaseName string
}

func (q *Queries) updateDownlinkLoss(ctx context.Context, arg updateDownlinkLossParams) error {
	_, err := q.db.ExecContext(ctx, updateDownlinkLoss, arg.Profile, arg.ConfigName, arg.TestPhaseName)
	return err
}

const updateUplinkLoss = `-- name: updateUplinkLoss :exec
Update "UplinkLoss" set "Profile"  = ?
where "ConfigName" like ? and "TestPhaseName" like ?
`

type updateUplinkLossParams struct {
	Profile       string
	ConfigName    string
	TestPhaseName string
}

func (q *Queries) updateUplinkLoss(ctx context.Context, arg updateUplinkLossParams) error {
	_, err := q.db.ExecContext(ctx, updateUplinkLoss, arg.Profile, arg.ConfigName, arg.TestPhaseName)
	return err
}
