// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package resultsDB

import (
	"database/sql"
)

type CableLoss struct {
	CableID     int64
	Date        string
	Time        string
	CableName   string
	CableLength float64
	Loss        string
}

type Result struct {
	TestID       int64
	SatName      string
	TestPhase    string
	TestType     string
	TestCategory sql.NullString
	ConfigName   string
	Date         string
	Time         string
	Remark       sql.NullString
	Report       string
	FilePath     string
	CSVFilePath  sql.NullString
}

type Stability struct {
	ID   int64
	Date string
	Time string
}

type StabilityValue struct {
	ID               int64
	StabilityID      int64
	TimeStampInteger int64
	TimeStamp        string
	Description      string
	Value            float64
}

type TSMInternalLoss struct {
	LossID               int64
	InputPort            string
	OutputPort           string
	PathMnemonic         sql.NullString
	MeasuredLosses       string
	MeasurementCompleted string
}

type TVACCableLoss struct {
	CableID   int64
	Date      string
	Time      string
	CableName string
	TestPhase string
	Reference string
	Loss      string
}

type UpDownConverter struct {
	ID       int64
	Name     string
	TestType string
	Date     sql.NullString
	Time     sql.NullString
	Results  string
}
