// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queryResults.sql

package resultsDB

import (
	"context"
	"database/sql"
)

const checkIfCableLossPMReferenceExists = `-- name: checkIfCableLossPMReferenceExists :one
Select Count("CableID") From "CableLosses"
Where "CableName" = "PM"
`

func (q *Queries) checkIfCableLossPMReferenceExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfCableLossPMReferenceExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkIfTVACCableAsReferenceExists = `-- name: checkIfTVACCableAsReferenceExists :one
Select Count("CableID") From "TVACCableLosses"
Where "Reference" = "1"
`

func (q *Queries) checkIfTVACCableAsReferenceExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfTVACCableAsReferenceExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkIfTVACCableLossPMReferenceExists = `-- name: checkIfTVACCableLossPMReferenceExists :one
Select Count("CableID") From "TVACCableLosses"
Where "CableName" = "PM"
`

func (q *Queries) checkIfTVACCableLossPMReferenceExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfTVACCableLossPMReferenceExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearTSMInternalLoss = `-- name: clearTSMInternalLoss :exec
Delete from "TSMInternalLoss"
`

func (q *Queries) clearTSMInternalLoss(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTSMInternalLoss)
	return err
}

const getAllResultsForConverter = `-- name: getAllResultsForConverter :many
Select ID, Name, TestType, Date, Time, Results from "UpDownConverter" where "Name" like ?
Order by "ID" Desc
`

func (q *Queries) getAllResultsForConverter(ctx context.Context, name string) ([]UpDownConverter, error) {
	rows, err := q.db.QueryContext(ctx, getAllResultsForConverter, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpDownConverter
	for rows.Next() {
		var i UpDownConverter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TestType,
			&i.Date,
			&i.Time,
			&i.Results,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTSMInternalLoss = `-- name: getAllTSMInternalLoss :many
Select LossID, InputPort, OutputPort, PathMnemonic, MeasuredLosses, MeasurementCompleted from "TSMInternalLoss"
Order by "InputPort" ASC
`

func (q *Queries) getAllTSMInternalLoss(ctx context.Context) ([]TSMInternalLoss, error) {
	rows, err := q.db.QueryContext(ctx, getAllTSMInternalLoss)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TSMInternalLoss
	for rows.Next() {
		var i TSMInternalLoss
		if err := rows.Scan(
			&i.LossID,
			&i.InputPort,
			&i.OutputPort,
			&i.PathMnemonic,
			&i.MeasuredLosses,
			&i.MeasurementCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCableLossForTSMInternalLoss = `-- name: getCableLossForTSMInternalLoss :one
Select "MeasuredLosses" from "TSMInternalLoss"
where "PathMnemonic" like "Cable-Measurement"
`

func (q *Queries) getCableLossForTSMInternalLoss(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getCableLossForTSMInternalLoss)
	var MeasuredLosses string
	err := row.Scan(&MeasuredLosses)
	return MeasuredLosses, err
}

const getCableLosses = `-- name: getCableLosses :many
Select CableID, Date, Time, CableName, CableLength, Loss from "CableLosses"
`

func (q *Queries) getCableLosses(ctx context.Context) ([]CableLoss, error) {
	rows, err := q.db.QueryContext(ctx, getCableLosses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CableLoss
	for rows.Next() {
		var i CableLoss
		if err := rows.Scan(
			&i.CableID,
			&i.Date,
			&i.Time,
			&i.CableName,
			&i.CableLength,
			&i.Loss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCableNames = `-- name: getCableNames :many
Select distinct "CableName" from "TVACCableLosses"
`

func (q *Queries) getCableNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var CableName string
		if err := rows.Scan(&CableName); err != nil {
			return nil, err
		}
		items = append(items, CableName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCableNamesForCableLoss = `-- name: getCableNamesForCableLoss :many
Select distinct "CableName" from "CableLosses"
`

func (q *Queries) getCableNamesForCableLoss(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCableNamesForCableLoss)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var CableName string
		if err := rows.Scan(&CableName); err != nil {
			return nil, err
		}
		items = append(items, CableName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctConvertersFromResultDB = `-- name: getDistinctConvertersFromResultDB :many
SELECT DISTINCT "Name" FROM "UpDownConverter"
`

func (q *Queries) getDistinctConvertersFromResultDB(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctConvertersFromResultDB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Name string
		if err := rows.Scan(&Name); err != nil {
			return nil, err
		}
		items = append(items, Name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasuredTSMInternalLoss = `-- name: getMeasuredTSMInternalLoss :one
Select "PathMnemonic","MeasuredLosses" from "TSMInternalLoss"
where "InputPort" = ? and "OutputPort" = ?
`

type getMeasuredTSMInternalLossParams struct {
	InputPort  string
	OutputPort string
}

type getMeasuredTSMInternalLossRow struct {
	PathMnemonic   sql.NullString
	MeasuredLosses string
}

func (q *Queries) getMeasuredTSMInternalLoss(ctx context.Context, arg getMeasuredTSMInternalLossParams) (getMeasuredTSMInternalLossRow, error) {
	row := q.db.QueryRowContext(ctx, getMeasuredTSMInternalLoss, arg.InputPort, arg.OutputPort)
	var i getMeasuredTSMInternalLossRow
	err := row.Scan(&i.PathMnemonic, &i.MeasuredLosses)
	return i, err
}

const getOfflineTestPhases = `-- name: getOfflineTestPhases :many
Select DISTINCT "TestPhase" from "Results"
Order by "TestID" desc
`

func (q *Queries) getOfflineTestPhases(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getOfflineTestPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var TestPhase string
		if err := rows.Scan(&TestPhase); err != nil {
			return nil, err
		}
		items = append(items, TestPhase)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPMOffsetForTSMInternalLoss = `-- name: getPMOffsetForTSMInternalLoss :one
Select "MeasuredLosses" from "TSMInternalLoss"
where "PathMnemonic" like "PM-Measurement"
`

func (q *Queries) getPMOffsetForTSMInternalLoss(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPMOffsetForTSMInternalLoss)
	var MeasuredLosses string
	err := row.Scan(&MeasuredLosses)
	return MeasuredLosses, err
}

const getPMReference = `-- name: getPMReference :one
Select "Loss" from "CableLosses"
where "CableName" like "PM"
`

func (q *Queries) getPMReference(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPMReference)
	var Loss string
	err := row.Scan(&Loss)
	return Loss, err
}

const getResults = `-- name: getResults :many
Select TestID, SatName, TestPhase, TestType, TestCategory, ConfigName, Date, Time, Remark, Report, FilePath, CSVFilePath from "Results"
where "TestPhase" like ? and "TestType" like ? and "TestCategory" like ?
and  "ConfigName" like ? and "Date" like ?
Order by "TestID" Desc
`

type getResultsParams struct {
	TestPhase    string
	TestType     string
	TestCategory sql.NullString
	ConfigName   string
	Date         string
}

func (q *Queries) getResults(ctx context.Context, arg getResultsParams) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, getResults,
		arg.TestPhase,
		arg.TestType,
		arg.TestCategory,
		arg.ConfigName,
		arg.Date,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.TestID,
			&i.SatName,
			&i.TestPhase,
			&i.TestType,
			&i.TestCategory,
			&i.ConfigName,
			&i.Date,
			&i.Time,
			&i.Remark,
			&i.Report,
			&i.FilePath,
			&i.CSVFilePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleResult = `-- name: getSingleResult :one
Select TestID, SatName, TestPhase, TestType, TestCategory, ConfigName, Date, Time, Remark, Report, FilePath, CSVFilePath FROM "Results"
WHERE "Date" = ? AND "Time" = ?
`

type getSingleResultParams struct {
	Date string
	Time string
}

func (q *Queries) getSingleResult(ctx context.Context, arg getSingleResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, getSingleResult, arg.Date, arg.Time)
	var i Result
	err := row.Scan(
		&i.TestID,
		&i.SatName,
		&i.TestPhase,
		&i.TestType,
		&i.TestCategory,
		&i.ConfigName,
		&i.Date,
		&i.Time,
		&i.Remark,
		&i.Report,
		&i.FilePath,
		&i.CSVFilePath,
	)
	return i, err
}

const getStabilityID = `-- name: getStabilityID :one
Select "ID" From "Stability"
Where "Date" = ? and "Time" = ?
`

type getStabilityIDParams struct {
	Date string
	Time string
}

func (q *Queries) getStabilityID(ctx context.Context, arg getStabilityIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStabilityID, arg.Date, arg.Time)
	var ID int64
	err := row.Scan(&ID)
	return ID, err
}

const getStabilityParameters = `-- name: getStabilityParameters :many
Select Distinct "Description" from "StabilityValues"
where "StabilityID" = ?
`

func (q *Queries) getStabilityParameters(ctx context.Context, stabilityid int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStabilityParameters, stabilityid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var Description string
		if err := rows.Scan(&Description); err != nil {
			return nil, err
		}
		items = append(items, Description)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStabilityPoints = `-- name: getStabilityPoints :many
Select ID, StabilityID, TimeStampInteger, TimeStamp, Description, Value from "StabilityValues"
where "StabilityID" = ? and "Description" = ?
`

type getStabilityPointsParams struct {
	StabilityID int64
	Description string
}

func (q *Queries) getStabilityPoints(ctx context.Context, arg getStabilityPointsParams) ([]StabilityValue, error) {
	rows, err := q.db.QueryContext(ctx, getStabilityPoints, arg.StabilityID, arg.Description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StabilityValue
	for rows.Next() {
		var i StabilityValue
		if err := rows.Scan(
			&i.ID,
			&i.StabilityID,
			&i.TimeStampInteger,
			&i.TimeStamp,
			&i.Description,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStabilitySessions = `-- name: getStabilitySessions :many
Select "ID", "Date", "Time" from "Stability"
Order by "ID" DESC
`

func (q *Queries) getStabilitySessions(ctx context.Context) ([]Stability, error) {
	rows, err := q.db.QueryContext(ctx, getStabilitySessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stability
	for rows.Next() {
		var i Stability
		if err := rows.Scan(&i.ID, &i.Date, &i.Time); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVACCableLosses = `-- name: getTVACCableLosses :many
Select CableID, Date, Time, CableName, TestPhase, Reference, Loss from "TVACCableLosses"
`

func (q *Queries) getTVACCableLosses(ctx context.Context) ([]TVACCableLoss, error) {
	rows, err := q.db.QueryContext(ctx, getTVACCableLosses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TVACCableLoss
	for rows.Next() {
		var i TVACCableLoss
		if err := rows.Scan(
			&i.CableID,
			&i.Date,
			&i.Time,
			&i.CableName,
			&i.TestPhase,
			&i.Reference,
			&i.Loss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVACPMReference = `-- name: getTVACPMReference :one
Select "Loss" from "TVACCableLosses"
where "CableName" like "PM"
`

func (q *Queries) getTVACPMReference(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTVACPMReference)
	var Loss string
	err := row.Scan(&Loss)
	return Loss, err
}

const getTVACReferenceCableLosses = `-- name: getTVACReferenceCableLosses :one
Select "Loss" from "TVACCableLosses" where "CableName" = ? and "Reference" = 1
`

func (q *Queries) getTVACReferenceCableLosses(ctx context.Context, cablename string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTVACReferenceCableLosses, cablename)
	var Loss string
	err := row.Scan(&Loss)
	return Loss, err
}

const getUpDownConverterResult = `-- name: getUpDownConverterResult :one
Select ID, Name, TestType, Date, Time, Results from "UpDownConverter"
where "TestType" like ? and "Name" like ?
Order by "ID" Desc Limit 1
`

type getUpDownConverterResultParams struct {
	TestType string
	Name     string
}

func (q *Queries) getUpDownConverterResult(ctx context.Context, arg getUpDownConverterResultParams) (UpDownConverter, error) {
	row := q.db.QueryRowContext(ctx, getUpDownConverterResult, arg.TestType, arg.Name)
	var i UpDownConverter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TestType,
		&i.Date,
		&i.Time,
		&i.Results,
	)
	return i, err
}

const getUpDownConverterResultWithDateAndTime = `-- name: getUpDownConverterResultWithDateAndTime :one
Select ID, Name, TestType, Date, Time, Results from "UpDownConverter"
where "Name" like ? and "Date" like ? and "Time" like ?
`

type getUpDownConverterResultWithDateAndTimeParams struct {
	Name string
	Date sql.NullString
	Time sql.NullString
}

func (q *Queries) getUpDownConverterResultWithDateAndTime(ctx context.Context, arg getUpDownConverterResultWithDateAndTimeParams) (UpDownConverter, error) {
	row := q.db.QueryRowContext(ctx, getUpDownConverterResultWithDateAndTime, arg.Name, arg.Date, arg.Time)
	var i UpDownConverter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TestType,
		&i.Date,
		&i.Time,
		&i.Results,
	)
	return i, err
}

const insertCableLossEntry = `-- name: insertCableLossEntry :exec
Insert into "CableLosses" ("Date", "Time", "CableName", "CableLength", "Loss")
Values (?,?,?,?,?)
`

type insertCableLossEntryParams struct {
	Date        string
	Time        string
	CableName   string
	CableLength float64
	Loss        string
}

func (q *Queries) insertCableLossEntry(ctx context.Context, arg insertCableLossEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertCableLossEntry,
		arg.Date,
		arg.Time,
		arg.CableName,
		arg.CableLength,
		arg.Loss,
	)
	return err
}

const insertResults = `-- name: insertResults :exec
Insert into "Results" ("SatName", "TestPhase", "TestType", "TestCategory", "ConfigName", "Date", "Time", "Remark", "Report", "FilePath", "CSVFilePath")
Values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type insertResultsParams struct {
	SatName      string
	TestPhase    string
	TestType     string
	TestCategory sql.NullString
	ConfigName   string
	Date         string
	Time         string
	Remark       sql.NullString
	Report       string
	FilePath     string
	CSVFilePath  sql.NullString
}

func (q *Queries) insertResults(ctx context.Context, arg insertResultsParams) error {
	_, err := q.db.ExecContext(ctx, insertResults,
		arg.SatName,
		arg.TestPhase,
		arg.TestType,
		arg.TestCategory,
		arg.ConfigName,
		arg.Date,
		arg.Time,
		arg.Remark,
		arg.Report,
		arg.FilePath,
		arg.CSVFilePath,
	)
	return err
}

const insertStability = `-- name: insertStability :one
Insert into "Stability" ("Date", "Time")
Values (?, ?) Returning "ID"
`

type insertStabilityParams struct {
	Date string
	Time string
}

func (q *Queries) insertStability(ctx context.Context, arg insertStabilityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStability, arg.Date, arg.Time)
	var ID int64
	err := row.Scan(&ID)
	return ID, err
}

const insertStabilityPoints = `-- name: insertStabilityPoints :exec
Insert into "StabilityValues" ("StabilityID", "TimeStampInteger", "TimeStamp", "Description", "Value")
Values (?, ?, ?, ?, ?)
`

type insertStabilityPointsParams struct {
	StabilityID      int64
	TimeStampInteger int64
	TimeStamp        string
	Description      string
	Value            float64
}

func (q *Queries) insertStabilityPoints(ctx context.Context, arg insertStabilityPointsParams) error {
	_, err := q.db.ExecContext(ctx, insertStabilityPoints,
		arg.StabilityID,
		arg.TimeStampInteger,
		arg.TimeStamp,
		arg.Description,
		arg.Value,
	)
	return err
}

const insertTSMInternalLoss = `-- name: insertTSMInternalLoss :exec
Insert into "TSMInternalLoss" ("LossID", "InputPort", "OutputPort", "PathMnemonic", "MeasuredLosses", "MeasurementCompleted")
values (?,?,?,?,?,'No')
`

type insertTSMInternalLossParams struct {
	LossID         int64
	InputPort      string
	OutputPort     string
	PathMnemonic   sql.NullString
	MeasuredLosses string
}

func (q *Queries) insertTSMInternalLoss(ctx context.Context, arg insertTSMInternalLossParams) error {
	_, err := q.db.ExecContext(ctx, insertTSMInternalLoss,
		arg.LossID,
		arg.InputPort,
		arg.OutputPort,
		arg.PathMnemonic,
		arg.MeasuredLosses,
	)
	return err
}

const insertTVACCableLossEntry = `-- name: insertTVACCableLossEntry :exec
Insert into "TVACCableLosses" ("Date", "Time", "CableName", "TestPhase", "Reference", "Loss")
Values (?,?,?,?,?,?)
`

type insertTVACCableLossEntryParams struct {
	Date      string
	Time      string
	CableName string
	TestPhase string
	Reference string
	Loss      string
}

func (q *Queries) insertTVACCableLossEntry(ctx context.Context, arg insertTVACCableLossEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertTVACCableLossEntry,
		arg.Date,
		arg.Time,
		arg.CableName,
		arg.TestPhase,
		arg.Reference,
		arg.Loss,
	)
	return err
}

const insertUpDownConverterResult = `-- name: insertUpDownConverterResult :exec
Insert into "UpDownConverter" ("Name", "TestType", "Date", "Time", "Results")
Values (?, ?, ?, ?, ?)
`

type insertUpDownConverterResultParams struct {
	Name     string
	TestType string
	Date     sql.NullString
	Time     sql.NullString
	Results  string
}

func (q *Queries) insertUpDownConverterResult(ctx context.Context, arg insertUpDownConverterResultParams) error {
	_, err := q.db.ExecContext(ctx, insertUpDownConverterResult,
		arg.Name,
		arg.TestType,
		arg.Date,
		arg.Time,
		arg.Results,
	)
	return err
}

const updateCableLossPMReference = `-- name: updateCableLossPMReference :exec
Update "CableLosses" Set "Date" = ?, "Time" = ?, "Loss" = ?
Where "CableName" = "PM"
`

type updateCableLossPMReferenceParams struct {
	Date string
	Time string
	Loss string
}

func (q *Queries) updateCableLossPMReference(ctx context.Context, arg updateCableLossPMReferenceParams) error {
	_, err := q.db.ExecContext(ctx, updateCableLossPMReference, arg.Date, arg.Time, arg.Loss)
	return err
}

const updateCableLossTSMInternalLoss = `-- name: updateCableLossTSMInternalLoss :exec
Update "TSMInternalLoss"  set "MeasuredLosses" = ?, "MeasurementCompleted" = 'Yes'
where "PathMnemonic" like "Cable-Measurement"
`

func (q *Queries) updateCableLossTSMInternalLoss(ctx context.Context, measuredlosses string) error {
	_, err := q.db.ExecContext(ctx, updateCableLossTSMInternalLoss, measuredlosses)
	return err
}

const updatePMOffsetTSMInternalLoss = `-- name: updatePMOffsetTSMInternalLoss :exec
Update "TSMInternalLoss"  set "MeasuredLosses" = ?, "MeasurementCompleted" = 'Yes'
where "PathMnemonic" like "PM-Measurement"
`

func (q *Queries) updatePMOffsetTSMInternalLoss(ctx context.Context, measuredlosses string) error {
	_, err := q.db.ExecContext(ctx, updatePMOffsetTSMInternalLoss, measuredlosses)
	return err
}

const updateResult = `-- name: updateResult :exec
UPDATE "Results"
SET "Report" = ?, "FilePath" = ?
WHERE "Date" = ? AND "Time" = ?
`

type updateResultParams struct {
	Report   string
	FilePath string
	Date     string
	Time     string
}

func (q *Queries) updateResult(ctx context.Context, arg updateResultParams) error {
	_, err := q.db.ExecContext(ctx, updateResult,
		arg.Report,
		arg.FilePath,
		arg.Date,
		arg.Time,
	)
	return err
}

const updateTSMInternalLoss = `-- name: updateTSMInternalLoss :exec
Update "TSMInternalLoss"  set "MeasuredLosses" = ?, "MeasurementCompleted" = 'Yes'
where "InputPort" = ? and "OutputPort" = ?
`

type updateTSMInternalLossParams struct {
	MeasuredLosses string
	InputPort      string
	OutputPort     string
}

func (q *Queries) updateTSMInternalLoss(ctx context.Context, arg updateTSMInternalLossParams) error {
	_, err := q.db.ExecContext(ctx, updateTSMInternalLoss, arg.MeasuredLosses, arg.InputPort, arg.OutputPort)
	return err
}

const updateTVACCableLossPMReference = `-- name: updateTVACCableLossPMReference :exec
Update "TVACCableLosses" Set "Date" = ?, "Time" = ?, "Reference" = ?, "Loss" = ?
Where "CableName" = "PM"
`

type updateTVACCableLossPMReferenceParams struct {
	Date      string
	Time      string
	Reference string
	Loss      string
}

func (q *Queries) updateTVACCableLossPMReference(ctx context.Context, arg updateTVACCableLossPMReferenceParams) error {
	_, err := q.db.ExecContext(ctx, updateTVACCableLossPMReference,
		arg.Date,
		arg.Time,
		arg.Reference,
		arg.Loss,
	)
	return err
}
